name: GitHub Actions CI App
run-name: ${{ github.actor }} is starting GitHub Actions CI App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install npm 6.x
        run: npm install -g npm@6
      - name: Install dependencies
        run: npm install
      - name: Make Install
        run: make install
