name: GitHub Actions CI App
run-name: ${{ github.actor }} is starting GitHub Actions CI App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm install -g npm@6
      - run: npm install
      - run: make setup
      - run: make test
      - run: make lint